version: "3.10"

services:
  db:
    container_name: postgres-db
    image: postgres:13-alpine
    restart: always
#    ports:
#      - 5432:5432
    volumes:
      - ./pgdb:/var/lib/postgresql/data
    env_file: .env
    environment:
      - LC_ALL=C.UTF-8
    networks:
      - nginx-proxy

  web_ahlak:
    container_name: ahlakvesunnetdergisi
    build: .
    restart: "always"
    ports:
      - "8050:8000"
    command: >
      sh -c "python manage.py makemigrations --noinput &&
             python manage.py migrate --noinput &&
             python manage.py collectstatic --noinput &&
             gunicorn core.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/code
      - ./static/:/code/static/
      - ./media/:/code/media/
    links:
      - db
    env_file: .env
    depends_on:
      - db
    networks:
      - nginx-proxy

networks:
  nginx-proxy:
    external: true
