# Generated by Django 5.1.4 on 2025-03-04 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Adres Başlığı')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Adres')),
                ('map', models.URLField(blank=True, max_length=600, null=True, verbose_name='Harita Linki')),
                ('work_time', models.CharField(blank=True, max_length=200, null=True, verbose_name='Açılıp kapanma saatleri')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Adresler',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='İsim Soyisim')),
                ('email', models.EmailField(max_length=254, verbose_name='Email adresi')),
                ('phone', models.CharField(max_length=50, verbose_name='Telefon Numarası')),
                ('subject', models.CharField(max_length=300, verbose_name='Mesajın Konusu')),
                ('message', models.TextField(verbose_name='Mesajın metni')),
                ('is_reply', models.BooleanField(blank=True, default=False, null=True, verbose_name='Cevaplandı mı?')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Mesajın geliş tarihi')),
            ],
            options={
                'verbose_name_plural': 'İletişim',
            },
        ),
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Email Başlığı')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Mailler',
            },
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon Başlığı')),
                ('phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telefon')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name_plural': 'Telefon Numraları',
            },
        ),
    ]
