# Generated by Django 5.1.4 on 2025-01-16 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='is_reply',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Cevaplandı mı?'),
        ),
    ]
