# Generated by Django 5.1.4 on 2025-03-04 13:23

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Adı')),
                ('name_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Adı')),
                ('name_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Adı')),
                ('name_kk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name_plural': 'Makale Kategorileri',
            },
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Makale Başlığı')),
                ('title_tr', models.CharField(blank=True, max_length=200, null=True, verbose_name='Makale Başlığı')),
                ('title_ar', models.CharField(blank=True, max_length=200, null=True, verbose_name='Makale Başlığı')),
                ('title_kk', models.CharField(blank=True, max_length=200, null=True, verbose_name='Makale Başlığı')),
                ('description', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_tr', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_ar', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama')),
                ('description_kk', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='Makale Resmi')),
                ('image_tr', models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='Makale Resmi')),
                ('image_ar', models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='Makale Resmi')),
                ('image_kk', models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='Makale Resmi')),
                ('author', models.CharField(blank=True, max_length=100, null=True, verbose_name='Makale Yazarı')),
                ('author_tr', models.CharField(blank=True, max_length=100, null=True, verbose_name='Makale Yazarı')),
                ('author_ar', models.CharField(blank=True, max_length=100, null=True, verbose_name='Makale Yazarı')),
                ('author_kk', models.CharField(blank=True, max_length=100, null=True, verbose_name='Makale Yazarı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('slug', models.SlugField(blank=True, null=True, unique=True, verbose_name='Slug')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.blogcategory', verbose_name='Kategori')),
            ],
            options={
                'verbose_name_plural': 'Makaleler',
            },
        ),
        migrations.CreateModel(
            name='BlogImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='Resim')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.blog', verbose_name='Blog')),
            ],
            options={
                'verbose_name_plural': 'Makale Alt Resimleri',
            },
        ),
    ]
