# Generated by Django 5.1.4 on 2025-03-05 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcategory_is_active_blogcategory_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_tr',
        ),
    ]
