# Generated by Django 5.1.4 on 2025-03-05 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_blogcategory_name_ar_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_kk',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_kk',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_tr',
        ),
    ]
