# Generated by Django 5.1.4 on 2025-03-05 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_remove_blog_author_ar_remove_blog_author_kk_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='language',
            field=models.CharField(blank=True, choices=[('tr', 'Turkish'), ('ar', 'Arabic'), ('kk', 'Kurdish')], default='tr', max_length=2, null=True, verbose_name='Dil'),
        ),
    ]
