# Generated by Django 5.1.4 on 2025-03-06 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_blog_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='language',
            field=models.CharField(blank=True, choices=[('tr', 'Türkçe'), ('ar', 'Arapça'), ('kk', 'Kürtçe')], default='tr', max_length=2, null=True, verbose_name='Dil'),
        ),
        migrations.AlterField(
            model_name='blogcategory',
            name='language',
            field=models.CharField(blank=True, choices=[('tr', 'Türkçe'), ('ar', 'Arapça'), ('kk', 'Kürtçe')], default='tr', max_length=2, null=True, verbose_name='Dil'),
        ),
    ]
