# Generated by Django 5.1.4 on 2025-08-11 18:36

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_blog_language_alter_blogcategory_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Makale Yazarı'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Makale Yazarı'),
        ),
        migrations.AddField(
            model_name='blog',
            name='author_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Makale Yazarı'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_ar',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_kk',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='description_tr',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_ar',
            field=models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='Makale Resmi'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_kk',
            field=models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='Makale Resmi'),
        ),
        migrations.AddField(
            model_name='blog',
            name='image_tr',
            field=models.ImageField(blank=True, null=True, upload_to='blog_img', verbose_name='Makale Resmi'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Makale Başlığı'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Makale Başlığı'),
        ),
        migrations.AddField(
            model_name='blog',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Makale Başlığı'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_ar',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_kk',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
        migrations.AddField(
            model_name='blogcategory',
            name='name_tr',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Kategori Adı'),
        ),
    ]
