# Generated by Django 5.1.4 on 2025-08-11 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_blog_author_ar_blog_author_kk_blog_author_tr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='author_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_kk',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_kk',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='description_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_kk',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='image_tr',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='title_tr',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_kk',
        ),
        migrations.RemoveField(
            model_name='blogcategory',
            name='name_tr',
        ),
    ]
