# Generated by Django 5.1.4 on 2025-01-16 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SEOModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Başlık')),
                ('description', models.TextField(help_text='İçeriğin kısa açıklaması (SEO ve Sosyal Medya için)', verbose_name='Açıklama')),
                ('keywords', models.CharField(blank=True, help_text='SEO için anahtar kelimeleri virgülle ayırarak girin.', max_length=300, verbose_name='Anahtar Kelimeler')),
                ('image', models.ImageField(blank=True, help_text='Sosyal medyada gösterilecek görsel.', null=True, upload_to='seo_images/', verbose_name='Görsel')),
                ('slug', models.SlugField(blank=True, unique=True, verbose_name='Slug')),
                ('twitter_handle', models.CharField(blank=True, help_text='Twitter kartları için kullanılır.', max_length=100, null=True, verbose_name='Twitter Kullanıcı Adı')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
            ],
            options={
                'verbose_name': 'SEO ve Sosyal Medya',
                'verbose_name_plural': 'SEO ve Sosyal Medya',
                'ordering': ['-created_at'],
            },
        ),
    ]
