# Generated by Django 5.1.4 on 2025-02-05 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_name', models.CharField(help_text='Səhifə adı (məs: Ana səhifə, Haqqımızda)', max_length=255)),
                ('slug', models.SlugField(help_text='Səhifənin unikal slug-u (məs: ana-səhifə, haqqimizda)', unique=True)),
                ('name', models.CharField(choices=[('author', 'Author'), ('description', 'Description'), ('keywords', 'Keywords'), ('robots', 'Robots'), ('viewport', 'Viewport'), ('og:title', 'Open Graph Title'), ('og:description', 'Open Graph Description'), ('og:image', 'Open Graph Image'), ('twitter:title', 'Twitter Title'), ('twitter:description', 'Twitter Description'), ('twitter:image', 'Twitter Image')], help_text='Meta name və ya property', max_length=50)),
                ('content', models.TextField(help_text='Meta tag dəyəri (content)')),
            ],
            options={
                'verbose_name_plural': 'SEO',
            },
        ),
        migrations.DeleteModel(
            name='SEO',
        ),
    ]
