# Generated by Django 5.1.4 on 2025-02-23 08:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='page_name',
            field=models.ForeignKey(blank=True, help_text='Ana sayfa için boş bırakınız. Sayfa adı (örnek: Hakkımızda, Servis, Blog, Galeri, İletişim)', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='base.navbaritem'),
        ),
        migrations.AlterField(
            model_name='pagebanner',
            name='page',
            field=models.CharField(blank=True, choices=[('home', 'Ana Sayfa'), ('about', 'Hakkımızda'), ('service', 'Hizmetler'), ('service_detail', 'Hizmet Detayları'), ('blog', 'Bloglar'), ('blog_detail', 'Blog Detayları'), ('galery', 'Galeri'), ('contact', 'İletişim'), ('error', 'Error')], max_length=20, null=True, unique=True, verbose_name='Sayfa'),
        ),
    ]
