# Generated by Django 5.1.4 on 2025-02-24 18:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMedia',
            fields=[
                ('datemodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='base.datemodel')),
                ('name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Sosyal Medya Başlığı')),
                ('url', models.CharField(blank=True, max_length=200, null=True, verbose_name='URL')),
                ('icon', models.CharField(blank=True, max_length=200, null=True, verbose_name='Icon')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktif mi?')),
            ],
            bases=('base.datemodel',),
        ),
        migrations.RemoveField(
            model_name='generalitem',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='generalitem',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='generalitem',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='generalitem',
            name='youtube',
        ),
    ]
