# Generated by Django 5.1.4 on 2025-03-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=10, null=True, verbose_name='Dil Kodu')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Dil Adı')),
                ('is_active', models.BooleanField(blank=True, default=True, null=True, verbose_name='Aktif mi?')),
            ],
            options={
                'verbose_name_plural': 'Diller',
            },
        ),
    ]
