# Generated by Django 5.1.4 on 2025-01-25 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_seomodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplatePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=255, unique=True, verbose_name='Sayfanın URL yolu')),
                ('template_name', models.CharField(choices=[('base/index', 'Ana Sayfa'), ('base/about', 'Hakkımızda'), ('service/services', 'Hizmetler'), ('service/service-details', 'Hizmet Detayları'), ('blog/blogs', 'Blog'), ('blog/blog-details', 'Blog Detayları')], max_length=50, verbose_name='Sayfa türü')),
                ('title', models.CharField(max_length=255, verbose_name='Sayfanın başlığı')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Sayfanın açıklaması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Sayfanın aktif olup olmadığını belirler')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Sayfanın oluşturulma tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Sayfanın güncellenme tarihi')),
            ],
            options={
                'verbose_name': 'Sayfa',
                'verbose_name_plural': 'Sayfalar',
            },
        ),
    ]
