# Generated by Django 5.1.4 on 2025-02-23 14:05

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_metatag_page_name_alter_pagebanner_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='galery',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Galeri Başlığı'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='content',
            field=models.TextField(blank=True, help_text='Meta tag içeriği (content)', null=True),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='name',
            field=models.CharField(blank=True, choices=[('author', 'Yazar'), ('description', 'Açıklama'), ('keywords', 'Anahtar Kelimeler'), ('robots', 'Robots'), ('viewport', 'Viewport'), ('og:title', 'Open Graph Başlığı'), ('og:description', 'Open Graph Açıklaması'), ('og:image', 'Open Graph Görseli'), ('twitter:title', 'Twitter Başlığı'), ('twitter:description', 'Twitter Açıklaması'), ('twitter:image', 'Twitter Görseli')], help_text='Meta adı veya özelliği', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='page_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='base.navbaritem'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='slug',
            field=models.SlugField(blank=True, help_text='Otomatik oluşturulur. Boş bırakınız.', null=True),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Statistik Bilgi Başlığı'),
        ),
        migrations.AlterField(
            model_name='statistic',
            name='value',
            field=models.IntegerField(blank=True, null=True, verbose_name='Statistik Değer'),
        ),
        migrations.AlterField(
            model_name='statisticinfo',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Açıklama'),
        ),
        migrations.AlterField(
            model_name='statisticinfo',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='statistic_img', verbose_name='Resim'),
        ),
        migrations.AlterField(
            model_name='statisticinfo',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Bilgi Başlığı'),
        ),
    ]
