# Generated by Django 5.1.4 on 2025-03-06 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dynamicpage',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='title_kk',
        ),
        migrations.RemoveField(
            model_name='dynamicpage',
            name='title_tr',
        ),
    ]
