# Generated by Django 5.1.4 on 2025-02-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_metatag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='page_name',
            field=models.CharField(blank=True, help_text='Səhifə adı.(məs: Ana Hakkimizda, Servis, Blog, Galeri İletisim) Ana Sayfa için boş saklayınız', max_length=255, null=True),
        ),
    ]
