# Generated by Django 5.1.4 on 2025-08-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_dynamicpage_title_ar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpage',
            name='title',
            field=models.CharField(blank=True, help_text='Bu bölümü tercüme yapmayınız.', max_length=200, null=True, verbose_name='Sayfa Adı'),
        ),
    ]
