# Generated by Django 5.1.4 on 2025-01-25 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_templatepage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SEOModel',
        ),
        migrations.AlterField(
            model_name='templatepage',
            name='template_name',
            field=models.CharField(choices=[('base/index', 'Ana Sayfa'), ('base/about', 'Hakkımızda'), ('base/galery', 'Galeri'), ('service/services', 'Hizmetler'), ('service/service-details', 'Hizmet Detayları'), ('blog/blogs', 'Blog'), ('blog/blog-details', 'Blog Detayları'), ('contact/contact', 'İletişim'), ('base/404', '404 Sayfası')], max_length=50, verbose_name='Sayfa türü'),
        ),
    ]
