# Generated by Django 5.1.4 on 2025-08-14 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_dynamicpage_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamicpage',
            name='title_ar',
            field=models.CharField(blank=True, help_text='Bu bölümü tercüme yapmayınız.', max_length=200, null=True, verbose_name='Sayfa Adı'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='title_kk',
            field=models.CharField(blank=True, help_text='Bu bölümü tercüme yapmayınız.', max_length=200, null=True, verbose_name='Sayfa Adı'),
        ),
        migrations.AddField(
            model_name='dynamicpage',
            name='title_tr',
            field=models.CharField(blank=True, help_text='Bu bölümü tercüme yapmayınız.', max_length=200, null=True, verbose_name='Sayfa Adı'),
        ),
    ]
