# Generated by Django 5.1.4 on 2025-01-25 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_delete_seomodel_alter_templatepage_template_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='templatepage',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Sayfanın URL yolu'),
        ),
    ]
