# Generated by Django 5.1.4 on 2025-08-14 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_dynamicpage_title_ar_dynamicpage_title_kk_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dynamicpage',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa Adı'),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='title_ar',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa Adı'),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='title_kk',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa Adı'),
        ),
        migrations.AlterField(
            model_name='dynamicpage',
            name='title_tr',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Sayfa Adı'),
        ),
    ]
