# Generated by Django 5.1.4 on 2025-02-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_metatag_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metatag',
            name='content',
            field=models.TextField(help_text='Meta tag içeriği (content)'),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='name',
            field=models.CharField(choices=[('author', 'Yazar'), ('description', 'Açıklama'), ('keywords', 'Anahtar Kelimeler'), ('robots', 'Robots'), ('viewport', 'Viewport'), ('og:title', 'Open Graph Başlığı'), ('og:description', 'Open Graph Açıklaması'), ('og:image', 'Open Graph Görseli'), ('twitter:title', 'Twitter Başlığı'), ('twitter:description', 'Twitter Açıklaması'), ('twitter:image', 'Twitter Görseli')], help_text='Meta adı veya özelliği', max_length=50),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='page_name',
            field=models.CharField(blank=True, help_text='Ana sayfa için boş bırakınız. Sayfa adı (örnek: Hakkımızda, Servis, Blog, Galeri, İletişim)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='metatag',
            name='slug',
            field=models.SlugField(blank=True, null=True),
        ),
    ]
