# Generated by Django 5.1.4 on 2025-02-19 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_navbaritem'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbaritem',
            name='position',
            field=models.CharField(blank=True, choices=[('both', 'Navbar və Footer'), ('navbar', 'Yalnız Navbar'), ('footer', 'Yalnız Footer')], default='both', max_length=30, null=True, verbose_name='Menyu yeri'),
        ),
    ]
