# Generated by Django 5.1.4 on 2025-03-04 13:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(help_text="Kanal ID'si", max_length=255, unique=True)),
                ('channel_name', models.CharField(help_text='Kanal Adı', max_length=255)),
                ('thumbnail', models.URLField(help_text='Kanal Resmi')),
            ],
            options={
                'verbose_name_plural': 'Kanallar',
            },
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playlist_id', models.CharField(help_text="Playlist ID'si", max_length=255, unique=True)),
                ('playlist_name', models.CharField(help_text='Playlist Adı', max_length=255)),
                ('thumbnail', models.URLField(help_text='Playlist Resmi')),
                ('is_active', models.BooleanField(blank=True, default=True, help_text='Aktif Mi?', null=True)),
                ('channel', models.ForeignKey(help_text='Kanal', on_delete=django.db.models.deletion.CASCADE, related_name='playlists', to='video.channel')),
            ],
            options={
                'verbose_name_plural': 'Oynatma Listeleri',
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.CharField(help_text="Video ID'si", max_length=255, unique=True)),
                ('title', models.CharField(help_text='Video Başlığı', max_length=255)),
                ('description', models.TextField(blank=True, help_text='Video Açıklaması', null=True)),
                ('thumbnail', models.URLField(help_text='Video Resmi')),
                ('url', models.URLField(help_text="Video URL'si")),
                ('duration', models.DurationField(blank=True, help_text='Video Süresi', null=True)),
                ('view_count', models.IntegerField(blank=True, help_text='Görüntülenme Sayısı', null=True)),
                ('like_count', models.IntegerField(blank=True, default=0, help_text='Beğeni Sayısı', null=True)),
                ('dislike_count', models.IntegerField(blank=True, default=0, help_text='Beğenmeme Sayısı', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Aktif Mi?')),
                ('published_at', models.DateTimeField(help_text='Yayınlanma Tarihi')),
                ('playlist', models.ForeignKey(blank=True, help_text='Playlist', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='video.playlist')),
            ],
            options={
                'verbose_name_plural': 'Videolar',
            },
        ),
    ]
