# Generated by Django 5.1.4 on 2025-03-05 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='playlist',
            name='languages',
            field=models.CharField(blank=True, choices=[('tr', 'Turkish'), ('ar', 'Arabic'), ('kk', 'Kurdish')], help_text='Seçilmiş dillər', max_length=255, null=True),
        ),
    ]
