# Generated by Django 5.1.4 on 2025-03-05 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0003_alter_playlist_languages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('tr', 'Turkish'), ('ar', 'Arabic'), ('kk', 'Kurdish')], max_length=2)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='playlist',
            name='languages',
        ),
        migrations.AddField(
            model_name='playlist',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Seçilmiş dillər', related_name='playlists', to='video.language'),
        ),
    ]
