# Generated by Django 5.1.4 on 2025-03-05 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0004_language_remove_playlist_languages_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playlist',
            name='languages',
        ),
        migrations.AddField(
            model_name='playlist',
            name='languages',
            field=models.CharField(blank=True, help_text='Seçilmiş dillər', max_length=255, null=True),
        ),
    ]
