# Generated by Django 5.1.4 on 2025-03-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0006_remove_language_name_remove_playlist_languages_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='language',
            options={'verbose_name_plural': 'Diller'},
        ),
        migrations.AlterField(
            model_name='playlist',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Seçilmiş dillər', related_name='playlists', to='video.language'),
        ),
    ]
