# Generated by Django 5.1.4 on 2025-03-05 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('video', '0007_alter_language_options_alter_playlist_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='languages',
            field=models.ManyToManyField(blank=True, help_text='Seçilmiş dillər', related_name='videos', to='video.language'),
        ),
    ]
