# Generated by Django 5.1.4 on 2025-01-25 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0003_templatepage'),
    ]

    operations = [
        migrations.CreateModel(
            name='MetaTags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('keywords', 'Anahtar Kelimeler (keywords)'), ('description', 'Açıklama (description)'), ('title', 'Başlık (title)'), ('author', 'Yazar (author)'), ('viewport', 'Görünüm Ayarları (viewport)')], max_length=30, verbose_name='Meta etiketinin türü (örn: keywords, description).')),
                ('content', models.TextField(verbose_name='Meta etiketinin içeriği (örn: anahtar kelimeler veya açıklama).')),
                ('is_active', models.BooleanField(default=True, verbose_name='Bu meta etiketinin aktif olup olmadığını belirler.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Meta etiketinin son güncellenme zamanı.')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta_tags', to='base.templatepage', verbose_name='Meta etiketinin bağlı olduğu sayfa.')),
            ],
            options={
                'verbose_name': 'Meta Etiketi',
                'verbose_name_plural': 'Meta Etiketleri',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='SocialTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_type', models.CharField(choices=[('og:title', 'Open Graph Başlık (og:title)'), ('og:description', 'Open Graph Açıklama (og:description)'), ('og:image', 'Open Graph Görsel (og:image)'), ('twitter:title', 'Twitter Başlık (twitter:title)'), ('twitter:description', 'Twitter Açıklama (twitter:description)'), ('twitter:image', 'Twitter Görsel (twitter:image)')], max_length=30, verbose_name="Etiket türünü seçin (örneğin, 'og:title', 'twitter:image').")),
                ('content', models.TextField(verbose_name="Etiket içeriği (örneğin, başlık, açıklama veya görsel URL'si).")),
                ('is_active', models.BooleanField(default=True, verbose_name='Bu etiketin aktif olup olmadığını belirler.')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Etiketin son güncellenme tarihi ve saati.')),
                ('template_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='social_tags', to='base.templatepage', verbose_name='Bu sosyal medya etiketinin bağlı olduğu sayfa.')),
            ],
            options={
                'verbose_name': 'Sosyal Medya Etiketi',
                'verbose_name_plural': 'Sosyal Medya Etiketleri',
                'ordering': ['-updated_at'],
            },
        ),
    ]
