name: Deploy AhlakSUnnetDergisi

on:
  push:
    branches: ["master"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.8.0
        with:
          ssh-private-key: ${{ secrets.SSH_KEY }}

      - name: Create .env file
        run: |
          echo "DEBUG='${{ secrets.DEBUG }}'" > .env
          echo "SECRET_KEY='${{ secrets.SECRET_KEY }}'">> .env

          echo "POSTGRES_DB='${{ secrets.POSTGRES_DB }}'" >> .env
          echo "POSTGRES_USER='${{ secrets.POSTGRES_USER }}'" >> .env
          echo "POSTGRES_PASSWORD='${{ secrets.POSTGRES_PASSWORD }}'" >> .env
          echo "POSTGRES_HOST='${{ secrets.POSTGRES_HOST }}'" >> .env
          echo "POSTGRES_PORT='${{ secrets.POSTGRES_PORT }}'" >> .env

          echo "EMAIL_BACKEND='${{ secrets.EMAIL_BACKEND }}'" >> .env
          echo "EMAIL_USE_TLS='${{ secrets.EMAIL_USE_TLS }}'" >> .env
          echo "EMAIL_HOST='${{ secrets.EMAIL_HOST }}'" >> .env
          echo "EMAIL_HOST_USER='${{ secrets.EMAIL_HOST_USER }}'" >> .env
          echo "EMAIL_HOST_PASSWORD='${{ secrets.EMAIL_HOST_PASSWORD }}'" >> .env
          echo "EMAIL_PORT='${{ secrets.EMAIL_PORT }}'" >> .env
          echo "DEFAULT_FROM_EMAIL='${{ secrets.DEFAULT_FROM_EMAIL }}'" >> .env

      - name: Copy .env to server
        run: |
          scp -o StrictHostKeyChecking=no .env ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/root/Ahlak-ve-Sunnet-Dergisi/.env

      - name: Deploy with Docker Compose
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
            cd /root/Ahlak-ve-Sunnet-Dergisi
            git fetch origin
            git pull --rebase origin master
            docker compose down --rmi local --remove-orphans
            docker compose up -d --build
            docker compose exec web_ahlak python manage.py makemigrations --noinput
            docker compose exec web_ahlak python manage.py migrate --noinput
            docker compose exec web_ahlak python manage.py collectstatic --noinput
          EOF
